config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'management#index'
  resources :management, only: :index do
    collection do
      resources :menus
      resources :store, only: [:show, :edit, :update]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :menus
  has_ancestry
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :menu

  # mount_uploader :image, ImagesUploader
end

app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many   :images
  has_one    :review
  has_many   :order_menus
  has_many   :orders, through: :order_menus
  belongs_to :timing
  belongs_to :category
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :order_menus
  has_many :menus, through: :order_menus
  belongs_to :user
end

app/models/order_menu.rb
# frozen_string_literal: true

class OrderMenu < ApplicationRecord
  belongs_to :menu
  belongs_to :order
end

app/models/pay.rb
# frozen_string_literal: true

class Pay < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :menu
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  geocoded_by :address
  # after_validation :geocode
end

app/models/timing.rb
# frozen_string_literal: true

class Timing < ApplicationRecord
  has_one :menu
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one  :pay
  has_many :orders
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/management_controller.rb
# frozen_string_literal: true

class ManagementController < ApplicationController
  def index
    @store = Store.find(1)
  end
end

app/controllers/menus_controller.rb
# frozen_string_literal: true

class MenusController < ApplicationController
end

app/controllers/store_controller.rb
# frozen_string_literal: true

class StoreController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update]

  def show
    gon.store = @store
    # @google_api = "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAP_API']}&callback=initMap"
  end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to store_path
    else
      render :edit
    end
  end

  private

  def store_params
    params.require(:store).permit(:zipcode, :address, :latitude, :longitude, :tel, :time, :holyday)
  end

  def set_store
    @store = Store.find(1)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/management_helper.rb
# frozen_string_literal: true

module ManagementHelper
end

app/helpers/menus_helper.rb
# frozen_string_literal: true

module MenusHelper
end

app/helpers/store_helper.rb
# frozen_string_literal: true

module StoreHelper
end

app/views/layouts/_gmap.html.haml
#map
%script{ async: "", src: @google_api }
:javascript
  let map;
  function initMap() {
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: gon.store.latitude,
        lng: gon.store.longitude
      },
      zoom: 20,
    });
    marker = new google.maps.Marker({
      position: {
        lat: gon.store.latitude,
        lng: gon.store.longitude
      },
      map: map
    });
  }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}
    %title SmartOrder
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "application"
  %body
    = yield

app/views/layouts/template/_gmap.html.haml
#map
  Gmap
%script{ async: "", src: @google_api }
:javascript
  let map;
  function initMap() {
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: gon.store.latitude,
        lng: gon.store.longitude
      },
      zoom: 20,
    });
    marker = new google.maps.Marker({
      position: {
        lat: gon.store.latitude,
        lng: gon.store.longitude
      },
      map: map
    });
  }

app/views/management/index.html.haml
= render "management/template/header"
.wrapper
  = render "management/template/side"
  .Main
    .Main__Contents
      .Cards
        .item
          .item__inner
            = render "management/template/store"
        .item
          .item__inner
        .item
          .item__inner
        .item
          .item__inner
        .item
          .item__inner

app/views/management/template/_header.html.haml
.Mg-header
  .Mg-header__bar-icon#mg-bar
    = icon("fas", "bars")
  .Mg-header__title
    = link_to management_index_path do
      SmartOrder
  .Mg-header__link
    = link_to "#" do
      ログアウト

app/views/management/template/_side.html.haml
.Side.off
  = link_to "#" do
    .Side__staff
      .Side__staff--image
      .Side__staff--name
        スタッフ

  = link_to management_index_path do
    .Side__link
      .icon
      トップ

  = link_to edit_store_path(1) do
    .Side__link
      .icon
        = material_icon.edit
      店舗情報編集

  = link_to menus_path do
    .Side__link
      .icon
        = material_icon.local_dining
      メニュー

  -# モーダル
  = link_to "#" do
    .Side__link
      .icon
      カテゴリー

  = link_to "#" do
    .Side__link
      .icon
      レビュー一覧

  = link_to "#" do
    .Side__link
      .icon
      注文一覧

  = link_to "#" do
    .Side__link
      .icon
      売上

  = link_to store_path(1) do
    .Side__link
      .icon
        = material_icon.map
      アクセス

app/views/management/template/_store.html.haml
.store
  .store__info
    .contents
      .contents__content
        .contents__content--info
          〒
          = @store.zipcode
      .contents__content
        .contents__content--info
          = @store.address
      .contents__content
        .contents__content--info
          ☎︎
          = @store.tel
      .contents__content
        .contents__content--info
          = @store.time
      .contents__content
        .contents__content--info
          = @store.holyday
      .contents__content
        = link_to edit_store_path(1) do
          編集

app/views/menus/edit.html.haml
%h1 edit

app/views/menus/new.html.haml
%h1= action_name

app/views/store/edit.html.haml
= render "management/template/header"
.wrapper
  = render "management/template/side"
  .Main
    .Main__Contents
      = form_with model: @store, local: true, id: "new_store" do |f|
        .Form
          .Form-title
            = @title
          .content
            .label
              郵便番号
            .field_control
              = f.text_field :zipcode, class: "field"
          .content
            .label
              住所
            .field_control
              = f.text_field :address, class: "field long"
          .content
            .label
              電話番号
            .field_control
              = f.text_field :tel, class: "field"
          .content
            .label
              営業時間
            .field_control
              = f.text_field :time, class: "field"
          .content
            .label
              定休日
            .field_control
              = f.text_field :holyday, class: "field"
          .content-submit
            = f.submit "編集", class: "submit"